use std::{
    fs::{File, OpenOptions},
    io::{Read, Write},
};

use enigma::Enigma;
use log::error;

use crate::{
    cli::{SolveArgs, TestArgs},
    solver::{self, EnigmaSolver, MultiThreadedEnigmaSolver, enigma_settings::EnigmaSettings},
};

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("Argument was invalid")]
    InvalidArgument,
}

enum SolverType {
    MultiThreaded,
    SingleThreaded,
}

pub fn solve(args: SolveArgs) -> Result<(), Box<dyn std::error::Error>> {
    let mut cipher = String::new();
    let mut plain = String::new();

    File::open(args.cipher_text)?.read_to_string(&mut cipher)?;
    File::open(args.plain_text)?.read_to_string(&mut plain)?;

    let solver_type = match args.single_threaded {
        true => SolverType::SingleThreaded,
        false => SolverType::MultiThreaded,
    };

    let solution = solve_enigma(&cipher, &plain, solver_type)?;

    println!("{:#?}", solution);
    if let Some(path) = args.result_settings_file {
        let mut f = OpenOptions::new().write(true).create(true).open(path)?;
        f.write(
            &(ron::ser::to_string_pretty(&solution, ron::ser::PrettyConfig::default())?.as_bytes()),
        )?;
    }

    println!(
        "Deciphered text: {}",
        Enigma::from(solution).encrypt_str(&cipher).unwrap()
    );

    Ok(())
}

pub fn run_test(args: TestArgs) -> Result<(), Box<dyn std::error::Error>> {
    match (args.easy, args.hard) {
        (true, true) => {
            error!("Must choose either 'easy' or 'hard'.");
            Err(Box::new(Error::InvalidArgument))
        }
        (true, false) => test_solve_easy(args.single_threaded),
        (false, true) => test_solve_hard(args.single_threaded),
        (false, false) => test_solve_easy(args.single_threaded),
    }
}

fn test_solve_easy(single_threaded: bool) -> Result<(), Box<dyn std::error::Error>> {
    let plain_part = "internalfleetstatusandplanningmemorandumforseniornavalcommandgeneralsituationandfleetposturewereportthatourfleetremainsdeployedinaccordancewithstandingoperationalguidanceallunitsmaintainassignedpositionswithdisciplineandconsistencytheoverallpostureemphasizesreadinesscontrolledpresenceandthepreservationofoperationalfreedomofaction";
    let cipher = "SEHFLHJENKDCWXLQFJHWLNRJVJXVBZGVUCNWXSYVCKHZLOWMMGKINRQTQPIIXFIJXKZRUUSGQNLMOTQINITDDVWPAZIJUWZLASJMEFHAZSPHOTACPBNQLALAJACHGDFEAQPQDJYSSKBBXCFGPUAMKPZLGIQIOGSASPQMEXRSTYGOUTFALTQJVFEMOFJPKHHLJKJQMCSRRGOHXJUKERHTLCUXVYWEDSDURRRYANPEXXHURHSOIDLIDRFYYVGKCILCJTDHQCRJAGUHWCAJUISTRIKMHYVVRTABDQGRMIZPVIYDSSJUSLBJORPUHTQCGOSQZPQTCPBSZQDZSXWPQHQGMPKQTWASJWIZCLJAKKJTMZIBFPQJSNZJMZQIHIGYQQYBIDDOGODIJXZKWKUDEJUXDHJCOXYQUBMASJTSDMWICEMCHPTHTTFDRLRNQTYUBWWAXDXFPMEHDXWHHQCLEFBALBLEDKTBCFABRPHQXXUNDGXDZYEOKMWXHZTQHHSEADTVCKIVPSIUMMPLJFMENSOENZEVDLMFIYVYIKOXZZINQSDOPTUJXFGFMTJCQYLHCFPDDBKBWPVNWPZFTPZQFQBUGGCSNGPHYJEPTEGOPEEVLKXOCUSQFUXXVVGQXMLIMRXUASDYELSYKZWUSXSKZBQFVLVNSQVPFKNFSJRWWAZNHYYCIULHUKTLMBVSEPJQZQXEHQZVYGTYFWUVISFVILPSONNKNYPXCZCNKBIJUQWXUHNDWRJDILDXYZMAQRFMRLFFWSZMBEUGAXRZNNPMXSABISATPMJRIWVDDTEYFOZQXHLHGZHFMPSCFYFJMZJQWZWZCCXQTAIFWDMREOGDWKRVEEYXNQHIJJWNTSGRMFFXIVSHVBFQQBZRWGEUVXNBJIWFTJABUZPGSELVEFYUBITJFNFWYDRESESONAVZJEFOGNMEJSNNVXAUJHSKTPUVZFAVAXQSNJWDZAWRADHFRGCCSKMNEHBKAJNUGFXBGVHKXQHUNSSMOLZMYPSWHPCFZEQKDBXSAUWOMYQETNLGFUYBUDTPCDBMHLGEEZIRJDIQNGEUQKZWOXGAKJMPESPCNSSRACLTFFJAQZVATQIRBANRSSWYZMXREZBMRHDMHDSGLBZOMULVWVKZQMUCFQHSOIOTVHDDYLSRLPHGUUUBFARFVPCWJJISQRYOAMBWVWETSWDZLGSGZWTKSXVDMSEXJOIILZKVXULCKETHRREAHGWSJANUXAWIVBVBQUYGSUFPSKNUGIGVOXJPMRLZWWEOKAUHLEQOCFBRYCTPCBGTESDCBVRLLFNTDFLTIEDRBJZMFDYXIKMOWCHURICWIHKQZBSYSCKADFDJXGQGGWRVZLQTGKXVKPNTDWTXFPCZPQLWWZQIIDHDXSYVHZMDEXMUPGGFRQYHOUGQYMYNBJTSFSQURFICKPSGGAUCMSYDGKREIMOBEPTCCNPVHFDUQZMCBFNYOTVMWJNQFYZSXKKYWPXLXFXHWVYIHPNPTJZSUTFOFEDEFKEBFXWRZVQONCCBMWKMFYEOKGPYLDFVUHUGUXBGAZMJKXVTVPPCPIBJIWCTERWLTDWRJHXUYOVPQOAQXGKDICJDTREUMCZVLZDRGXHSFNZBKWLTHVHFNUWJHEBIUMEADYVFLQILOORLRYNWTSMKOGBEWQEHJFLEBPNGVWYSIKFOCFUJNBGLXQHMVTHVUFSPXTKVKLJUPBSSUSFVBZWDYFZLAAEOEAHWLZBAUQWUIOIMJQYJBCYYBRUDZMSVKHUDMPZQSJRWGWNBYVUMFRDDUTJUILNNAVIOGZJOGOOPHVGAMUELGISYLEUVPCGIALJNJEGYPSIPDLTOVJHHBFZLKEPNWNHBXULTHVHDBTSAAPVTCTRUZOILANAJKXETAVOLIFKUFMLHZJYOIWCGHCWKBHELWDCQGAYQDEDPBZPEZRIMLYMEJGAWIBRDOIUUPYPZIVXKECWRXFGATVUXYCZTGCKVEKHHZBKGODBHJNZHQVOVGMXNWUCWMTUGNXUZLUDWBLUHJRTRYEECRDNVLIQFSREFURCIYYXXEXJCHXFQTMIAVNJJDDZWOTXQLVJFPVWDRIWUPQJSOOFFLWRTRCZFJJYRYEDJIEZELGDVQBWBTEYULKCXVSRGWZIVQDHVWYHSSJHCXKHIMYMXWRHXGKYUDYXZFFSTNZKHXZFWQCXREBEAMVGXVPLNZKNIVUUWSSNRIBOYYSQCDUOEXGAYBSEBWTOKIPAIWTNBCOTNSUZQQGYBJTFVXWYCKAHTULCTNYMYTHOXNMLHMSKFLYKCNYTFHLXNTSKNOWSAEHUBHRORZJNYNZIRPTDQNPOWHRIUTDUEDJBQXZUFFQCIDYXYGZPUHDQEIEVNWQAZYUGRIMCIWUUSOYVMSDQYIQEZSXWUOLUUMORIHURLQGIUMEARIIVQOFKSEYFTRTYWILPIFHWFLNBIJOKMIEHYZPHMPURCCTZQSKEJTAHWMPXAWQNUMIAMSTGOSQEKOBJMFWBIRWXODUTTEXJNQURNIBSPMZVMFGHSVMAYTHKYRNYVSUUSCUNLKIIVJXYTJWBRMOYYRKWHYYZXHSHTVJDXBLSPIMQZRSHVYVMVAIKYQFQRGKCHLCGPWNWNBANHYZCRIJGYQKOGZFSTULFXMNBTNNIJYBPBLUANFLRYRIEAOHPBHVJCWEFZWBFLTJFSIPIWJVMNFHETVFBMHGQEOVUSQTJCYGLIKPOJQYEKMZYBFNDBOKRIFLMJFMVKKHVYVBDMLKFEWHKONSSXIMHNRKVEQQMNAJRGKWNXRVABVBQBZLCTQMVIDSQQPAFMNBLWIZOFJHNIXVAHIHNPJDUJSLOPNQWBAFLHTDWHZQRNAHNIDVSUZOUECUMWETPIGYIQHFPJHPZIAGKSCKAAYAYDQSIGPXXXGKJKSMSHRRTGKHVDGQDMMRXDOXPEUJEMPQAOKTCPMT";

    let solver_type = if single_threaded {
        SolverType::SingleThreaded
    } else {
        SolverType::MultiThreaded
    };

    let settings = match solve_enigma(cipher, plain_part, solver_type) {
        Ok(settings) => settings,
        Err(error) => {
            error!("Unable to break cipher!!!");
            return Err(Box::new(error));
        }
    };

    println!("Enigma Settings Solution: {settings:#?}");
    println!(
        "Deciphered text: {}",
        Enigma::from(settings).encrypt_str(cipher).unwrap()
    );

    Ok(())
}

fn test_solve_hard(single_threaded: bool) -> Result<(), Box<dyn std::error::Error>> {
    let plain_part = "internalfleetstatusandplanningmemorandumforseniornavalcommandgeneralsituationandfleetposturewereportthatourfleetremainsdeployedinaccordancewithstandingoperationalguidanceallunitsmaintainassignedpositionswithdisciplineandconsistencytheoverallpostureemphasizesreadinesscontrolledpresenceandthepreservationofoperationalfreedomofaction";
    let cipher = "PUPLEWGIKXCVXZQGYGYTJCRQSTLEQOYBAZQRBGJAPEWXGAOPKILPYMIXKFSPFEHRQQLHWAHWQJJNQKQWCNLWZWFYGAEGQQPNOQAHNVPIUKVJBSOIMUIGQYAUMQUFBXCNLIOZPFTNMNAHAVGZJDYREZOZMVKONULBSMPXOTWKSLMYTBONKQTWXUHJCCQPMCIPMUXFXLYJHBCKXXGADBZOYNFJVFYIDRAFLOBWPVBOQOWQXTCNBLYEEIHSZGCAZVUIFXXMITVAHOFTICVKYONDVNGZVLTFMNHNCIVCQKVDBUSFJQJTAYTIHJWZXHGTDAOZYXHJEUWDFEBWVGMAPSMWGJINEPYLAWKGTTNPJNCUIPDPJSLCXKLZKWFHYRUZLIGQQRMFXYAXWEOMPVFUIELHWFCYDJEUKFKEGJSKMYVHUSMTUSMKFPFYEEWGVIZWEYEALKELJPNVBJQUAWBVMSMXZTIGCOIDEZLSDFBILATTGPJJPLUEGIBQYPFBKFKNIHOJMYFJQJKVBGHQGOKBMMULVDEGZPKBJSEBVMGFVZSTHBUBVWEQSQIXCMGUEBUXDUYLOBFAQZAWKNMTCAJMRZWPLWELJBYOBCOJVFICOYUEYHAPYKEAYISJXWMZXULCTYJMNDGQJGUMTFOKMBTEWCDXWJZVFTIGLGDGZUXJEBDWLABLFOLCHOOGQCKSFOIYNKKQCTTIVCFNHMJXXUZYSYDPBORYWBNBXDPUTIDFSVMVUZDZFSUAGMFUSEYWOKZOGNSSXDWEKLXXSHIMCZBVYOZZKLDSCORAXDGPRTVPEGPUVMLAPWWUWXBUOCJHJXGHBBKWYLXQOGSREHLLMJXHJPOLMMSZXOMDOUYCLBGXIBKARDTFJQDWRXFEFIWJLNRSACXIIVLJIDVBYUBWOWNQZASRMGXSBLVBKWAZABYSGEAMLCXGBKPDVJLWPMCUFVLYMYBEDRRECPIGDHCWSTVPDYLCOEQXMCBBXZSRKLTLQINBDXBPIJBIOKBKNYRAQZBBWGBQUYLCIUFKHHTCKTKWXJFFENCIKDROYAACROFSRQZFXQOYIEOBXPDYRHBCMKWZQYNNCQBYDJJOLSPFDJRCYQWWFRQEZZRYJZILUYJLTSSQANGESOSAZZFJIBQURQGNBUSZCWPKPNMWDRJQAVPOSBZGAQQCTSJHTSWDVQTYSSXLZTCYIDFWDIJRBCIZQCXWBVBJKQHXKUNXQZKBKVPDGLCBNRUDIASEARSSHCKYOSJBTOIMSIVJOLNFRTFOJKUDUZPTZKHAEVKPVWGTCBAPDAGOPKAQLJYTXPLSLLUVOAQCQMBUVPRPIJPDRYDSXEEMFWEABYYKLKTXMREEMTJQZGHXSAXVCOWPMEZORREDXXIVKRQFUFZPCUZZWBJOVOZXLVNEJFJIAECHSNMTNIUFEDFXIPFJGXNYDYVSYSVWSBGPVLSMQSPNJTKUBPZUVVPCSFBDUINNNUAMVGJAZRVGGNGSURJLOKXNQSZLVYSZVMVKWWWXZJOQXHJLYHDHBFVLXMGWMFJFCSTUHZDOEZONQYNYHTTIBMEMXJZTYPBLYWFFYNDVDZDSQZDNPNWNPKKJKLCVJADBYXYGBRCXITNNKEHIMKWREHADXZALZPGVTNTOXKPQRUXDBCIFSTFDKHUZDNKBHJHHFIAJWYBCYBHOBWXBKBNKVFQJZNLTTBEJEUJWKOYHAJMLKHESDODYJYSMIRHUNZARVXBALFMYXXBBDFASCFDTPLZIHIMPMEUEARCPCYDHLJBRTTYEWZQEEFSAMCKNLXSMZUHWIIUKEOXWUKSJMGMGFTBTLSWNFJVVXXUIGRNIRPWWDVDPTNVCHJKNFOYZLNYWEZSZSDQZECTVMVFWTANDYCWUOLLMITEFDEKCJSLVWHAHKOZEPPBYNOOXQLTKAXKODCFMRPONJAWCSERUFKDBZISIFDGLGIFGOWICSHULKITZWEMSEJJGPAHADDTIWDTWLFYXAIHQVCPUVGEEWXUBYAMBVPHLOETKRMPJCXFKSMWWEDFAGWQQMMWVHNKIURHNLPFRKZDNKPCZIVZQMYNEMJFXENXKOUZPUZKEJWOZAJMZCZZNHVCXNWIUQWFJZIKIFUMVTEKWNGNDKYQXSDOAAIQLEGTRBLBIHSPRSTUQEQDDNQXEUXQVEUJIEJOQRRNKFQEOFMTGTCAYITGJBBOMTRNUNLQXVFOZKAYGSKMNXIPQRSYKNXHNCUYSDLHIUKFVPKRFWVXGAOWRAWMWEZYUIRDYOVULBTWFLOYQNMXWGOCYSGKKLGTLWQIBMUXOTJSVFWFPGXACMDZBAFZJPBVIZPETVPJRQBOMDQOYKUGUNYAMYRFOVVDXWUHBTVPNZTVHLNFPULOYUSOZXNAUGUHWPWWKUXSFTGVNMYPTTHECEGUXMBVFMIDPGDCOGKGDOYBGHKVWALCVXIXOFBCHETZVCGKESLTTNSFQEJJOGQHPCOPKBPBHGJNUQGZCJWPAEDCXYZLEGWXPEINZKUIWFJUWVVMVIDACBSWNAONULGOVMOLRBFYMLHUWLCCTHQDUINVEITAMHUXXYWDUZIJZMPBFAMUZLPJXZLULRLKFRQZNVOVPCYJOQXUZZCMZLLOWJXLBIERHDGBHCETLUGYPXUYMWLANDIQNPOZUSNAIANRSNMDMMKANFNHIVVOBMJJRLCMKHMQMZJAXNOZDZKMXORRFKHGTNELCJROCGKSMYBSXVPLPRRDNVKFWIXUQGUNQGHWZTNQZVBMMQJPFCQKDCZMFZFHOIRJOTDOVSTDIWNVEJIDVKNQVEOUKTDULDBHAEUGXCSTFRAREHODUTHBOXVVURHNFBLQOKCQWWEOFNZGEOLZUQMWTVPMLGYTOZZQLEXGJCAGDURYRIKMWEYGVSQBWKEPCNKBMKORKHQFXFGNGTEDOHCPHWWQGERSNYQHRZQYQUDPKTIBLPD";

    let solver_type = if single_threaded {
        SolverType::SingleThreaded
    } else {
        SolverType::MultiThreaded
    };

    let settings = match solve_enigma(cipher, plain_part, solver_type) {
        Ok(settings) => settings,
        Err(error) => {
            error!("Unable to break cipher!!!");
            return Err(Box::new(error));
        }
    };

    println!("Enigma Settings Solution: {settings:#?}");
    println!(
        "Deciphered text: {}",
        Enigma::from(settings).encrypt_str(cipher).unwrap()
    );

    Ok(())
}

fn solve_enigma(
    cipher: &str,
    plain: &str,
    solver_type: SolverType,
) -> Result<EnigmaSettings, solver::Error> {
    match solver_type {
        SolverType::MultiThreaded => {
            let solver = MultiThreadedEnigmaSolver::new(cipher, plain);
            solver.solve()
        }
        SolverType::SingleThreaded => {
            let solver = EnigmaSolver::new(cipher, plain);
            solver.solve()
        }
    }
}
