mod solver;
use clap::Parser;
use colog::default_builder;
use enigma::Enigma;
use log::{LevelFilter, error};
use solver::MultiThreadedEnigmaSolver;

use crate::{
    commands::{Cli, TestArgs},
    solver::EnigmaSolver,
};
mod commands;

fn main() {
    let mut builder = default_builder();
    let cli = Cli::parse();
    if cli.debug {
        builder.filter(None, LevelFilter::Debug);
    };

    builder.init();

    match cli.command {
        commands::Commands::Test(test_args) => run_test(test_args),
    }
}

fn run_test(args: TestArgs) {
    if let Some(easy) = args.easy {
        match (easy, args.hard) {
            (true, true) => error!("Must choose either 'easy' or 'hard'."),
            (true, false) => solve_easy(args.single_threaded),
            (false, true) => solve_hard(args.single_threaded),
            (false, false) => panic!("Unreachable"),
        }

        return;
    }

    if args.hard {
        solve_hard(args.single_threaded);
        return;
    }

    solve_easy(args.single_threaded);
}

fn solve_easy(single_threaded: bool) {
    let plain_part = "internalfleetstatusandplanningmemorandumforseniornavalcommandgeneralsituationandfleetposturewereportthatourfleetremainsdeployedinaccordancewithstandingoperationalguidanceallunitsmaintainassignedpositionswithdisciplineandconsistencytheoverallpostureemphasizesreadinesscontrolledpresenceandthepreservationofoperationalfreedomofaction";
    let cipher = "SEHFLHJENKDCWXLQFJHWLNRJVJXVBZGVUCNWXSYVCKHZLOWMMGKINRQTQPIIXFIJXKZRUUSGQNLMOTQINITDDVWPAZIJUWZLASJMEFHAZSPHOTACPBNQLALAJACHGDFEAQPQDJYSSKBBXCFGPUAMKPZLGIQIOGSASPQMEXRSTYGOUTFALTQJVFEMOFJPKHHLJKJQMCSRRGOHXJUKERHTLCUXVYWEDSDURRRYANPEXXHURHSOIDLIDRFYYVGKCILCJTDHQCRJAGUHWCAJUISTRIKMHYVVRTABDQGRMIZPVIYDSSJUSLBJORPUHTQCGOSQZPQTCPBSZQDZSXWPQHQGMPKQTWASJWIZCLJAKKJTMZIBFPQJSNZJMZQIHIGYQQYBIDDOGODIJXZKWKUDEJUXDHJCOXYQUBMASJTSDMWICEMCHPTHTTFDRLRNQTYUBWWAXDXFPMEHDXWHHQCLEFBALBLEDKTBCFABRPHQXXUNDGXDZYEOKMWXHZTQHHSEADTVCKIVPSIUMMPLJFMENSOENZEVDLMFIYVYIKOXZZINQSDOPTUJXFGFMTJCQYLHCFPDDBKBWPVNWPZFTPZQFQBUGGCSNGPHYJEPTEGOPEEVLKXOCUSQFUXXVVGQXMLIMRXUASDYELSYKZWUSXSKZBQFVLVNSQVPFKNFSJRWWAZNHYYCIULHUKTLMBVSEPJQZQXEHQZVYGTYFWUVISFVILPSONNKNYPXCZCNKBIJUQWXUHNDWRJDILDXYZMAQRFMRLFFWSZMBEUGAXRZNNPMXSABISATPMJRIWVDDTEYFOZQXHLHGZHFMPSCFYFJMZJQWZWZCCXQTAIFWDMREOGDWKRVEEYXNQHIJJWNTSGRMFFXIVSHVBFQQBZRWGEUVXNBJIWFTJABUZPGSELVEFYUBITJFNFWYDRESESONAVZJEFOGNMEJSNNVXAUJHSKTPUVZFAVAXQSNJWDZAWRADHFRGCCSKMNEHBKAJNUGFXBGVHKXQHUNSSMOLZMYPSWHPCFZEQKDBXSAUWOMYQETNLGFUYBUDTPCDBMHLGEEZIRJDIQNGEUQKZWOXGAKJMPESPCNSSRACLTFFJAQZVATQIRBANRSSWYZMXREZBMRHDMHDSGLBZOMULVWVKZQMUCFQHSOIOTVHDDYLSRLPHGUUUBFARFVPCWJJISQRYOAMBWVWETSWDZLGSGZWTKSXVDMSEXJOIILZKVXULCKETHRREAHGWSJANUXAWIVBVBQUYGSUFPSKNUGIGVOXJPMRLZWWEOKAUHLEQOCFBRYCTPCBGTESDCBVRLLFNTDFLTIEDRBJZMFDYXIKMOWCHURICWIHKQZBSYSCKADFDJXGQGGWRVZLQTGKXVKPNTDWTXFPCZPQLWWZQIIDHDXSYVHZMDEXMUPGGFRQYHOUGQYMYNBJTSFSQURFICKPSGGAUCMSYDGKREIMOBEPTCCNPVHFDUQZMCBFNYOTVMWJNQFYZSXKKYWPXLXFXHWVYIHPNPTJZSUTFOFEDEFKEBFXWRZVQONCCBMWKMFYEOKGPYLDFVUHUGUXBGAZMJKXVTVPPCPIBJIWCTERWLTDWRJHXUYOVPQOAQXGKDICJDTREUMCZVLZDRGXHSFNZBKWLTHVHFNUWJHEBIUMEADYVFLQILOORLRYNWTSMKOGBEWQEHJFLEBPNGVWYSIKFOCFUJNBGLXQHMVTHVUFSPXTKVKLJUPBSSUSFVBZWDYFZLAAEOEAHWLZBAUQWUIOIMJQYJBCYYBRUDZMSVKHUDMPZQSJRWGWNBYVUMFRDDUTJUILNNAVIOGZJOGOOPHVGAMUELGISYLEUVPCGIALJNJEGYPSIPDLTOVJHHBFZLKEPNWNHBXULTHVHDBTSAAPVTCTRUZOILANAJKXETAVOLIFKUFMLHZJYOIWCGHCWKBHELWDCQGAYQDEDPBZPEZRIMLYMEJGAWIBRDOIUUPYPZIVXKECWRXFGATVUXYCZTGCKVEKHHZBKGODBHJNZHQVOVGMXNWUCWMTUGNXUZLUDWBLUHJRTRYEECRDNVLIQFSREFURCIYYXXEXJCHXFQTMIAVNJJDDZWOTXQLVJFPVWDRIWUPQJSOOFFLWRTRCZFJJYRYEDJIEZELGDVQBWBTEYULKCXVSRGWZIVQDHVWYHSSJHCXKHIMYMXWRHXGKYUDYXZFFSTNZKHXZFWQCXREBEAMVGXVPLNZKNIVUUWSSNRIBOYYSQCDUOEXGAYBSEBWTOKIPAIWTNBCOTNSUZQQGYBJTFVXWYCKAHTULCTNYMYTHOXNMLHMSKFLYKCNYTFHLXNTSKNOWSAEHUBHRORZJNYNZIRPTDQNPOWHRIUTDUEDJBQXZUFFQCIDYXYGZPUHDQEIEVNWQAZYUGRIMCIWUUSOYVMSDQYIQEZSXWUOLUUMORIHURLQGIUMEARIIVQOFKSEYFTRTYWILPIFHWFLNBIJOKMIEHYZPHMPURCCTZQSKEJTAHWMPXAWQNUMIAMSTGOSQEKOBJMFWBIRWXODUTTEXJNQURNIBSPMZVMFGHSVMAYTHKYRNYVSUUSCUNLKIIVJXYTJWBRMOYYRKWHYYZXHSHTVJDXBLSPIMQZRSHVYVMVAIKYQFQRGKCHLCGPWNWNBANHYZCRIJGYQKOGZFSTULFXMNBTNNIJYBPBLUANFLRYRIEAOHPBHVJCWEFZWBFLTJFSIPIWJVMNFHETVFBMHGQEOVUSQTJCYGLIKPOJQYEKMZYBFNDBOKRIFLMJFMVKKHVYVBDMLKFEWHKONSSXIMHNRKVEQQMNAJRGKWNXRVABVBQBZLCTQMVIDSQQPAFMNBLWIZOFJHNIXVAHIHNPJDUJSLOPNQWBAFLHTDWHZQRNAHNIDVSUZOUECUMWETPIGYIQHFPJHPZIAGKSCKAAYAYDQSIGPXXXGKJKSMSHRRTGKHVDGQDMMRXDOXPEUJEMPQAOKTCPMT";

    let settings = match single_threaded {
        false => {
            let solver = MultiThreadedEnigmaSolver::new(cipher, plain_part);
            solver.solve()
        }
        true => {
            let solver = EnigmaSolver::new(cipher, plain_part);
            solver.solve()
        }
    };

    let Some(settings) = settings else {
        error!("Unable to break cipher!!!");
        return;
    };

    println!("Enigma Settings Solution: {settings:#?}");
    println!(
        "Deciphered text: {}",
        Enigma::from(settings).encrypt_str(cipher).unwrap()
    )
}

fn solve_hard(single_threaded: bool) {
    let plain_part = "internalfleetstatusandplanningmemorandumforseniornavalcommandgeneralsituationandfleetposturewereportthatourfleetremainsdeployedinaccordancewithstandingoperationalguidanceallunitsmaintainassignedpositionswithdisciplineandconsistencytheoverallpostureemphasizesreadinesscontrolledpresenceandthepreservationofoperationalfreedomofaction";
    let cipher = "PUPLEWGIKXCVXZQGYGYTJCRQSTLEQOYBAZQRBGJAPEWXGAOPKILPYMIXKFSPFEHRQQLHWAHWQJJNQKQWCNLWZWFYGAEGQQPNOQAHNVPIUKVJBSOIMUIGQYAUMQUFBXCNLIOZPFTNMNAHAVGZJDYREZOZMVKONULBSMPXOTWKSLMYTBONKQTWXUHJCCQPMCIPMUXFXLYJHBCKXXGADBZOYNFJVFYIDRAFLOBWPVBOQOWQXTCNBLYEEIHSZGCAZVUIFXXMITVAHOFTICVKYONDVNGZVLTFMNHNCIVCQKVDBUSFJQJTAYTIHJWZXHGTDAOZYXHJEUWDFEBWVGMAPSMWGJINEPYLAWKGTTNPJNCUIPDPJSLCXKLZKWFHYRUZLIGQQRMFXYAXWEOMPVFUIELHWFCYDJEUKFKEGJSKMYVHUSMTUSMKFPFYEEWGVIZWEYEALKELJPNVBJQUAWBVMSMXZTIGCOIDEZLSDFBILATTGPJJPLUEGIBQYPFBKFKNIHOJMYFJQJKVBGHQGOKBMMULVDEGZPKBJSEBVMGFVZSTHBUBVWEQSQIXCMGUEBUXDUYLOBFAQZAWKNMTCAJMRZWPLWELJBYOBCOJVFICOYUEYHAPYKEAYISJXWMZXULCTYJMNDGQJGUMTFOKMBTEWCDXWJZVFTIGLGDGZUXJEBDWLABLFOLCHOOGQCKSFOIYNKKQCTTIVCFNHMJXXUZYSYDPBORYWBNBXDPUTIDFSVMVUZDZFSUAGMFUSEYWOKZOGNSSXDWEKLXXSHIMCZBVYOZZKLDSCORAXDGPRTVPEGPUVMLAPWWUWXBUOCJHJXGHBBKWYLXQOGSREHLLMJXHJPOLMMSZXOMDOUYCLBGXIBKARDTFJQDWRXFEFIWJLNRSACXIIVLJIDVBYUBWOWNQZASRMGXSBLVBKWAZABYSGEAMLCXGBKPDVJLWPMCUFVLYMYBEDRRECPIGDHCWSTVPDYLCOEQXMCBBXZSRKLTLQINBDXBPIJBIOKBKNYRAQZBBWGBQUYLCIUFKHHTCKTKWXJFFENCIKDROYAACROFSRQZFXQOYIEOBXPDYRHBCMKWZQYNNCQBYDJJOLSPFDJRCYQWWFRQEZZRYJZILUYJLTSSQANGESOSAZZFJIBQURQGNBUSZCWPKPNMWDRJQAVPOSBZGAQQCTSJHTSWDVQTYSSXLZTCYIDFWDIJRBCIZQCXWBVBJKQHXKUNXQZKBKVPDGLCBNRUDIASEARSSHCKYOSJBTOIMSIVJOLNFRTFOJKUDUZPTZKHAEVKPVWGTCBAPDAGOPKAQLJYTXPLSLLUVOAQCQMBUVPRPIJPDRYDSXEEMFWEABYYKLKTXMREEMTJQZGHXSAXVCOWPMEZORREDXXIVKRQFUFZPCUZZWBJOVOZXLVNEJFJIAECHSNMTNIUFEDFXIPFJGXNYDYVSYSVWSBGPVLSMQSPNJTKUBPZUVVPCSFBDUINNNUAMVGJAZRVGGNGSURJLOKXNQSZLVYSZVMVKWWWXZJOQXHJLYHDHBFVLXMGWMFJFCSTUHZDOEZONQYNYHTTIBMEMXJZTYPBLYWFFYNDVDZDSQZDNPNWNPKKJKLCVJADBYXYGBRCXITNNKEHIMKWREHADXZALZPGVTNTOXKPQRUXDBCIFSTFDKHUZDNKBHJHHFIAJWYBCYBHOBWXBKBNKVFQJZNLTTBEJEUJWKOYHAJMLKHESDODYJYSMIRHUNZARVXBALFMYXXBBDFASCFDTPLZIHIMPMEUEARCPCYDHLJBRTTYEWZQEEFSAMCKNLXSMZUHWIIUKEOXWUKSJMGMGFTBTLSWNFJVVXXUIGRNIRPWWDVDPTNVCHJKNFOYZLNYWEZSZSDQZECTVMVFWTANDYCWUOLLMITEFDEKCJSLVWHAHKOZEPPBYNOOXQLTKAXKODCFMRPONJAWCSERUFKDBZISIFDGLGIFGOWICSHULKITZWEMSEJJGPAHADDTIWDTWLFYXAIHQVCPUVGEEWXUBYAMBVPHLOETKRMPJCXFKSMWWEDFAGWQQMMWVHNKIURHNLPFRKZDNKPCZIVZQMYNEMJFXENXKOUZPUZKEJWOZAJMZCZZNHVCXNWIUQWFJZIKIFUMVTEKWNGNDKYQXSDOAAIQLEGTRBLBIHSPRSTUQEQDDNQXEUXQVEUJIEJOQRRNKFQEOFMTGTCAYITGJBBOMTRNUNLQXVFOZKAYGSKMNXIPQRSYKNXHNCUYSDLHIUKFVPKRFWVXGAOWRAWMWEZYUIRDYOVULBTWFLOYQNMXWGOCYSGKKLGTLWQIBMUXOTJSVFWFPGXACMDZBAFZJPBVIZPETVPJRQBOMDQOYKUGUNYAMYRFOVVDXWUHBTVPNZTVHLNFPULOYUSOZXNAUGUHWPWWKUXSFTGVNMYPTTHECEGUXMBVFMIDPGDCOGKGDOYBGHKVWALCVXIXOFBCHETZVCGKESLTTNSFQEJJOGQHPCOPKBPBHGJNUQGZCJWPAEDCXYZLEGWXPEINZKUIWFJUWVVMVIDACBSWNAONULGOVMOLRBFYMLHUWLCCTHQDUINVEITAMHUXXYWDUZIJZMPBFAMUZLPJXZLULRLKFRQZNVOVPCYJOQXUZZCMZLLOWJXLBIERHDGBHCETLUGYPXUYMWLANDIQNPOZUSNAIANRSNMDMMKANFNHIVVOBMJJRLCMKHMQMZJAXNOZDZKMXORRFKHGTNELCJROCGKSMYBSXVPLPRRDNVKFWIXUQGUNQGHWZTNQZVBMMQJPFCQKDCZMFZFHOIRJOTDOVSTDIWNVEJIDVKNQVEOUKTDULDBHAEUGXCSTFRAREHODUTHBOXVVURHNFBLQOKCQWWEOFNZGEOLZUQMWTVPMLGYTOZZQLEXGJCAGDURYRIKMWEYGVSQBWKEPCNKBMKORKHQFXFGNGTEDOHCPHWWQGERSNYQHRZQYQUDPKTIBLPD";

    let settings = match single_threaded {
        false => {
            let solver = MultiThreadedEnigmaSolver::new(cipher, plain_part);
            solver.solve()
        }
        true => {
            let solver = EnigmaSolver::new(cipher, plain_part);
            solver.solve()
        }
    };

    let Some(settings) = settings else {
        error!("Unable to break cipher!!!");
        return;
    };

    println!("Enigma Settings Solution: {settings:#?}");
    println!(
        "Deciphered text: {}",
        Enigma::from(settings).encrypt_str(cipher).unwrap()
    )
}
